---
title: "Take-home Midterm"
author: "Murat Kezer"
output: 
    html_document:
      code_download: TRUE
      toc: TRUE
      toc_float:
        collapsed: FALSE
      toc_depth: 3
      code_folding: hide
---

```{r include=F}
knitr::opts_chunk$set(echo = TRUE, 
                      tidy = TRUE, 
                      cache = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

options(scipen = 99)
```


```{r, cache = FALSE, results = 'hide', message = FALSE}
library(tidyverse)
library(janitor)
library(gapr)
library(ggtext)

theme_set(theme_minimal())
```


# Part A: Data {.tabset .tabset-fade}
## 1. Download and clean data

```{r}
download_file <- function(year) {
  link <- glue::glue("https://www.oregon.gov/ode/educator-resources/assessment/TestResults20{year}/pagr_schools_ela_raceethnicity_{year-1}{year}.xlsx")
  rio::import(link, setclass = "tibble", na = c("-", "--", "*"))
}

# download data
df <- map_dfr(15:18, download_file)

# data cleaning
df %>% 
  clean_names() %>% 
  names()

df <- df %>% 
  clean_names() %>% 
  filter(student_group %in% c("White", "Hispanic/Latino")) %>% 
  select(academic_year, district, school, student_group, grade_level, 
         starts_with("number_level")) %>% 
  drop_na(number_level_1, number_level_2, number_level_3, number_level_4) %>%
  pivot_longer(cols = starts_with("number_level"),
               names_to = "level",
               values_to = "n",
               names_prefix = "number_level_"
               ) %>% 
  mutate(n = as.numeric(n))

head(df, n = 10)
```

## 2. Compute variables

```{r}
df <-
df %>%
  group_by(district) %>% 
  mutate(n_schools = length(unique(school))) %>% 
  ungroup() %>% 
  group_by(academic_year, district, student_group, level, n_schools) %>% 
  summarise(n = sum(n, na.rm = TRUE)) %>% 
  ungroup() %>%
	pivot_wider(names_from = "student_group",
		          values_from = "n") %>%
	clean_names() %>%
	drop_na(hispanic_latino, white) %>%
  mutate(across(hispanic_latino:white, as.integer)) %>% 
  select(academic_year, district, n_schools, level, everything())

head(df)
```

# Part B: Achievement gaps {.tabset .tabset-fade}
## 1. Average achievement differences
```{r}
# nest
by_district <- df %>%
	group_by(academic_year, district, n_schools) %>%
	nest() 

models_nest <- by_district %>% 
	mutate(models = map(data, ~ estimate_v(.x, 
	                                       "white", "hispanic_latino"))) %>% 
  select(-data) %>% 
  unnest(models) %>% 
  rename(auc_nest = auc,
         v_nest = v,
         v_se_nest = v_se)

# nest_by
models_nest_by <- df %>%
	nest_by(academic_year, district, n_schools) %>%
  summarize(models = estimate_v(data, "white", "hispanic_latino")) %>% 
  mutate(auc_nest_by = models$auc,
         v_nest_by = models$v,
         v_se_nest_by = models$v_se) %>% 
  select(-models)
```

## 2. Plot
```{r}
nest_and_nest_by <- left_join(models_nest, models_nest_by) 

nest_and_nest_by %>% 
  ggplot(aes(v_nest_by, v_nest)) +
  geom_point(size = 4,
             color = "gray30") +
  geom_line(color = "light blue",
            size = 2) +
  labs(x = "V (`nest_by() %>% summarize()`)",
       y = "V (`group_by() %>% nest() %>% mutate() %>% map()`)") +
  scale_y_continuous(expand = c(.1, .1))
```

## 3. Plot 2
```{r}
first_100_districts <- unique(models_nest$district)[1:100]

models_plot <- models_nest %>% 
  filter(district %in% first_100_districts) %>% 
  mutate(v_above_zero = if_else(v_nest > 0, "#640C90", "#57DBF4"),
         academic_year = as.factor(academic_year),
         academic_year = as.numeric(academic_year))
```

### Using nest_by and summarize
```{r}
plots_nest_by <-
  models_plot %>% 
  ungroup() %>% 
  nest_by(district) %>% 
  summarise(plot_nest_by = list(
    ggplot(data, aes(academic_year, v_nest)) +
      geom_hline(yintercept = 0,
                 color = "red") +
      geom_line() +
      geom_errorbar(aes(ymin = v_nest + qnorm(0.025)*v_se_nest,
                        ymax = v_nest + qnorm(0.975)*v_se_nest),
                    width = 0.25) +
      geom_point(aes(color = v_above_zero),
                 size = 2.5) +
      scale_color_identity() +
      scale_x_continuous(breaks = 1:4,
                         labels = c("2014-2015", "2015-2016",
                                    "2016-2017", "2017-2018")) +
      labs(title = glue::glue("Achievement Gap Estimates: {district}"),
           subtitle = "Negative values indicate <span style='color:#57DBF4'>White</span> students have higher average achievement <br/>Positive values indicate <span style='color:#640C90'>Hispanic/Latino</span> students have higher average achievement",
           caption = glue::glue("Note: District included {unique(data$n_schools)} schools."),
           x = "School year",
           y = "Average achievement difference (SD units)")   +
      theme(plot.title.position = "plot",
            plot.subtitle = element_markdown(),
            legend.position = "none"
      )
    )
  )

plots_nest_by$plot_nest_by[[1]]
```

### Using pmap
```{r}
plots_pmap <- models_plot %>% 
  group_by(district, n_schools) %>% 
  nest() %>% 
  mutate(plots = pmap(list(data, district, n_schools), 
                     function(.data, .district, .n_schools)
    ggplot(.data, aes(academic_year, v_nest)) +
      geom_hline(yintercept = 0, 
	               color = "red") +
      geom_line() +
      geom_errorbar(aes(ymin = v_nest + qnorm(0.025)*v_se_nest,
                        ymax = v_nest + qnorm(0.975)*v_se_nest),
                    width = 0.25) +
      geom_point(aes(color = v_above_zero),
                 size = 2.5) +
      scale_color_identity() +
      scale_x_continuous(breaks = as.numeric(as.factor(.data$academic_year)), 
                         labels = .data$academic_year) +
      labs(title = glue::glue("Achievement Gap Estimates: {.district}"),
           subtitle = "Negative values indicate <span style='color:#57DBF4'>White</span> students have higher average achievement <br/>Positive values indicate <span style='color:#640C90'>Hispanic/Latino</span> students have higher average achievement",
           caption = glue::glue("Note: District included {.n_schools} schools."),
           x = "School year",
           y = "Average achievement difference (SD units)") + 
      theme( 
        plot.title.position = "plot",
        plot.subtitle = element_markdown()
      )
    )
  )
  
plots_pmap$plots[[1]]
```









